// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmFUcv0_iXmzT6Rs4pI3Ag62dTe0HTNM',
    appId: '1:374205829222:web:1b8c6ca1d427f8d930dda7',
    messagingSenderId: '374205829222',
    projectId: 'runcoach-494009',
    authDomain: 'runcoach-494009.firebaseapp.com',
    storageBucket: 'runcoach-494009.firebasestorage.app',
    measurementId: 'G-F5YQQ3RBBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBRRuZ0Dk4ollDTyCGkjtljDU92oVRLc',
    appId: '1:374205829222:android:d7c4c13fcdcb91f830dda7',
    messagingSenderId: '374205829222',
    projectId: 'runcoach-494009',
    storageBucket: 'runcoach-494009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkpM9Q8B98niIAbYqWbN3pn7lezsUMjF0',
    appId: '1:374205829222:ios:c7f96158d9422e9a30dda7',
    messagingSenderId: '374205829222',
    projectId: 'runcoach-494009',
    storageBucket: 'runcoach-494009.firebasestorage.app',
    iosBundleId: 'com.example.runcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkpM9Q8B98niIAbYqWbN3pn7lezsUMjF0',
    appId: '1:374205829222:ios:c7f96158d9422e9a30dda7',
    messagingSenderId: '374205829222',
    projectId: 'runcoach-494009',
    storageBucket: 'runcoach-494009.firebasestorage.app',
    iosBundleId: 'com.example.runcoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmFUcv0_iXmzT6Rs4pI3Ag62dTe0HTNM',
    appId: '1:374205829222:web:087c5b8b0ad0248730dda7',
    messagingSenderId: '374205829222',
    projectId: 'runcoach-494009',
    authDomain: 'runcoach-494009.firebaseapp.com',
    storageBucket: 'runcoach-494009.firebasestorage.app',
    measurementId: 'G-YXL32NF0P2',
  );
}
